---
title: "About me"
---


I studied mathematics at MIT and UC Berkeley. After graduating, I was a
NSF postdoc at Stanford University and a Visiting Assistant Professor in
Statistics at the University of Chicago, working in
<a href="http://www.sciencedirect.com/science/article/pii/S0747717105001173">statistics</a>,
<a href="http://www.ploscompbiol.org/doi/pcbi.1000074">population sequencing</a>, and
<a href="http://projecteuclid.org/euclid.bj/1194625594">viral</a>
<a href="http://www.biomedcentral.com/1471-2105/12/119">evolution.</a>
After that, I spent six years as a principal scientist at 23andMe,
where I studied the genetics of a wide range of complex traits, from
<a href="https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1002141">Parkinson's disease</a> to
<a href="http://www.flavourjournal.com/content/1/1/22/abstract">cilantro dislike.</a>
I became a data scientist at <a href="http://coursera.org">Coursera</a> in 2014,
where I worked to make online education more <a href="https://hbr.org/2015/09/whos-benefiting-from-moocs-and-why">effective</a>, available, and fun.
After a stint at <a href="http://calicolabs.com"> Calico</a> working on [longevity](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6752884/),
I returned to 23andMe, working on using ML and GWAS to enhance phenotypes and predict longitudinal health outcomes.
I'm now at insitro, using genetics and multi-modal phenotyping to better understand human disease.


## Research Interests

* Statistics, machine learning and discrete mathematics
* Complex trait genetics, genome-wide association studies, heritability, and sequencing
* Cancer tumor progression and HIV population evolution


## Experience and Education

* Director, Machine Learning Integrated Phenotyping; **insitro**, South San Francisco, CA (2024--present)
* Senior Health R\&D Scientist, **23andMe**, Sunnyvale, CA (2018--2024)
* Principal Data Scientist, **Calico Labs**, South San Francisco, CA (2016--2018)
* Data Scientist, **Coursera**, Mountain View, CA (2014--2016)
* Principal Scientist, Statistical Genetics, **23andMe**, Mountain View, CA (2008--2014)
* Visiting Assistant Professor, **University of Chicago**, Department of Statistics (2007--2008)
* Postdoctoral Research Fellow, **Stanford University**, Department of Statistics (2006--2007)
* Emphasis in Computational and Genomic Biology, **University of California, Berkeley** (2001--2006)
* Ph.D. Mathematics, **University of California, Berkeley** (2001--2006)
* S.B. Mathematics (Minor in Music), **Massachusetts Institute of Technology** (1997--2001)


## Honors and awards

* National Science Foundation Postdoctoral Research Fellowship --- Mathematical Sciences (2006--2008)
* Bernard Friedman Prize, University of California, Berkeley, top thesis in applied mathematics (2006)
* National Defense Science and Engineering Graduate Fellowship (2001--2004)
* Westinghouse Science Talent Search, Third Place (1997)
